[tool.poetry]
name = "gitflow1"
version = "0.1.0"
description = ""
authors = ["helonely <idravil1211@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
